### ISSUE TITLE
Move to HTTPS

### ISSUE THREAD

**Issue by phibar** [omoearth/omo-quantum#20]
- threads
- ipfs
- deployed page

**Comment by samuelandert** [comment]
Fix ws path for https to work
<img width="618" alt="Bildschirmfoto 2020-05-11 um 15 56 18" src="https://user-images.githubusercontent.com/747161/81569737-f522c080-939f-11ea-9cc2-2aca88a20cc6.png">

**Comment by samuelandert** [comment]
done
